/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hQP91eAUXkN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Prata } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Pagination, PaginationContent, PaginationItem, PaginationPrevious, PaginationLink, PaginationNext } from "@/components/ui/pagination"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ThreadContent() {
  return (
    <div className="flex flex-col w-full max-w-4xl mx-auto px-4 md:px-6 py-8">
      <div className="mb-6">
        <h1 className="text-3xl font-bold">Introducing the frontend cloud</h1>
        <p className="text-muted-foreground">Discuss the latest updates and features of the frontend cloud platform.</p>
      </div>
      <div className="grid gap-6">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">John Doe</div>
                <div className="text-xs text-muted-foreground">2 hours ago</div>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <p>
              Wow, this new frontend cloud platform looks amazing! I can't wait to try it out. The ability to deploy
              code on-demand without managing infrastructure is a game-changer.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Jane Smith</div>
                <div className="text-xs text-muted-foreground">1 day ago</div>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <p>
              I'm really excited about the real-time insights and controls provided by this platform. Being able to see
              granular, first-party metrics on site performance per deployment is going to be incredibly useful for my
              team.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Bob Johnson</div>
                <div className="text-xs text-muted-foreground">3 days ago</div>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <p>
              The personalization at the edge feature is really impressive. Being able to deliver dynamic, personalized
              content while ensuring users only see the best version of the site is a huge advantage.
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">Emily Davis</div>
                <div className="text-xs text-muted-foreground">1 week ago</div>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <p>
              I'm really impressed with the infinite scalability and zero config features of this platform. Being able
              to run code on-demand without needing to manage infrastructure or upgrade hardware is a huge time-saver.
            </p>
          </CardContent>
        </Card>
      </div>
      <div className="mt-8">
        <Pagination>
          <PaginationContent>
            <PaginationItem>
              <PaginationPrevious href="#">Previous</PaginationPrevious>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">1</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#" isActive>
                2
              </PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationNext href="#">Next</PaginationNext>
            </PaginationItem>
          </PaginationContent>
        </Pagination>
      </div>
      <div className="mt-8">
        <Card>
          <CardHeader>
            <CardTitle>Leave a comment</CardTitle>
          </CardHeader>
          <CardContent>
            <form className="grid gap-4">
              <div className="grid gap-1">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Your name" />
              </div>
              <div className="grid gap-1">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Your email" />
              </div>
              <div className="grid gap-1">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Your message" rows={4} />
              </div>
              <Button type="submit">Submit</Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
