name: frontend_test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Cache node modules
      uses: actions/cache@v4
      id: cache_dependency
      env:
        cache-name: cache-dependency
      with:
        path: "node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
      run: npm ci

    - name: Run jest
      run: npm test
